# Generated by Django 4.2 on 2024-05-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_remove_bankaccount_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.CharField(default='default_owner', max_length=255),
        ),
    ]
